swagger: '2.0'
info:
  title: JTHub Account Management Service API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
security:
  # enable OAuth protection for all REST endpoints
  # (only active if the TOKENINFO_URL environment variable is set)
  - oauth2: [uid]
paths:
  /accounts:
    get:
      tags: [Accounts]
      operationId: app.get_accounts
      summary: Get all accounts
      parameters:
        - name: limit
          in: query
          type: integer
          minimum: 0
          default: 100
        - name: offset
          in: query
          type: integer
          minimum: 0
          default: 0
      responses:
        200:
          description: Return accounts
          schema:
            type: array
            #items:
            #  $ref: '#/definitions/Account'
    post:
      tags: [Accounts]
      operationId: app.create_account
      summary: Create an account
      parameters:
        - name: account
          description: Account is an organization or individual
          in: body
          schema:
            $ref: '#/definitions/Account'
      responses:
        200:
          description: Account created
          schema:
            $ref: '#/definitions/Account'
        409:
          description: Account with specified name already exists
  /accounts/{account_name}:
    get:
      tags: [Accounts]
      operationId: app.get_account
      summary: Get a single account
      parameters:
        - $ref: '#/parameters/account_name'
      responses:
        200:
          description: Return account
          schema:
            $ref: '#/definitions/Account'
        404:
          description: Account does not exist
    put:
      tags: [Accounts]
      operationId: app.update_account
      summary: Update an account
      parameters:
        - $ref: '#/parameters/account_name'
        - name: account
          in: body
          schema:
            $ref: '#/definitions/Account'
      responses:
        200:
          description: Account updated
    delete:
      tags: [Accounts]
      operationId: app.delete_account
      summary: Remove an account
      parameters:
        - $ref: '#/parameters/account_name'
      responses:
        204:
          description: Account was deleted
        404:
          description: Account does not exist
  /accounts/{account_name}/members/{member_name}:
    get:
      tags: [Organization account members]
      operationId: app.get_member
      summary: Verify oragnization membership on a given member account
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/member_name'
      responses:
        200:
          description: Return member name and ID
        404:
          description: Member does not exist
    put:
      tags: [Organization account members]
      operationId: app.add_member
      summary: Add a member to an oragnization account
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/member_name'
      responses:
        200:
          description: Return member name and ID when member added
        204:
          description: Member already in the organization
        404:
          description: Member does not exist
    delete:
      tags: [Organization account members]
      operationId: app.delete_member
      summary: Remove a member from an oragnization account
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/member_name'
      responses:
        204:
          description: Member deleted from the organization
        404:
          description: Member does not exist


parameters:
  account_name:
    name: account_name
    description: Account's unique name
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-_]{3,30}$"
  member_name:
    name: member_name
    description: Member's account nanme
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-_]{3,30}$"


definitions:
  Account:
    type: object
    required:
      - name
    properties:
      name:
        type: string
        description: Account's name
        pattern: "^[a-zA-Z0-9-_]{3,30}$"
        example: "junjun-zhang"
        minLength: 3
        maxLength: 30
      tags:
        type: object
        description: Custom tags


securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
