swagger: '2.0'
info:
  title: JTHub Account Management Service API
  version: "0.1"
consumes:
  - application/json
produces:
  - application/json
security:
  # enable OAuth protection for all REST endpoints
  # (only active if the TOKENINFO_URL environment variable is set)
  - oauth2: [uid]
paths:
  /accounts:
    get:
      tags: [Accounts]
      operationId: app.get_accounts
      summary: Get all accounts
      parameters:
        - name: limit
          in: query
          type: integer
          minimum: 0
          default: 100
        - name: offset
          in: query
          type: integer
          minimum: 0
          default: 0
      responses:
        200:
          description: Return accounts
          schema:
            type: array
            #items:
            #  $ref: '#/definitions/Account'
  /accounts/{account_name}:
    get:
      tags: [Accounts]
      operationId: app.get_account
      summary: Get a single account
      parameters:
        - $ref: '#/parameters/account_name'
      responses:
        200:
          description: Return account
          schema:
            $ref: '#/definitions/Account'
        404:
          description: Account does not exist
    post:
      tags: [Accounts]
      operationId: app.create_account
      summary: Create an account
      parameters:
        - $ref: '#/parameters/account_name'
        - $ref: '#/parameters/account_type'
      responses:
        200:
          description: Account created
          schema:
            $ref: '#/definitions/Account'
        409:
          description: Account with specified name already exists
    put:
      tags: [Accounts]
      operationId: app.update_account
      summary: Update an account
      parameters:
        - $ref: '#/parameters/account_name'
        - name: account
          in: body
          schema:
            $ref: '#/definitions/Account'
      responses:
        200:
          description: Account updated
    delete:
      tags: [Accounts]
      operationId: app.delete_account
      summary: Remove an account
      parameters:
        - $ref: '#/parameters/account_name'
      responses:
        204:
          description: Account was deleted
        404:
          description: Account does not exist


parameters:
  account_name:
    name: account_name
    description: Account's unique name
    in: path
    type: string
    required: true
    pattern: "^[a-zA-Z0-9-_]+$"
  account_type:
    name: account_type
    description: Account is an organization or individual
    in: query
    type: string
    required: false
    pattern: "^[a-zA-Z0-9-_]+$"


definitions:
  Account:
    type: object
    required:
      - _name
      - _id
    properties:
      _id:
        type: string
        description: Unique identifier
        example: "7ebf7fa9-f70f-481a-a499-5fba3f8c5078"
        readOnly: true
      _name:
        type: string
        description: Account's name
        example: "junjun-zhang"
        minLength: 1
        maxLength: 100
      tags:
        type: object
        description: Custom tags
      created:
        type: string
        format: date-time
        description: Creation time
        example: "2015-07-07T15:49:51.230+02:00"
        readOnly: true


securityDefinitions:
  oauth2:
    type: oauth2
    flow: implicit
    authorizationUrl: https://example.com/oauth2/dialog
    scopes:
      uid: Unique identifier of the user accessing the service.
